README.md
relates #22
- create initial read me file
=> create inital readme file

client/src/components/common/Button/index.js, client/src/components/common/Button/style.css
=> Buttton Component

client/src/components/pages/About/index.js, client/src/components/pages/About/style.css
=> About page

client/package-lock.json, client/package.json, client/src/components/App/index.js, client/src/components/pages/TherapyType/index.js, client/src/components/pages/TherapyType/staticData.js, client/src/components/pages/TherapyType/style.css
=> Therapy Types Page

package-lock.json, package.json, server/database/config/airtableConnection.js, server/database/config/cloudinaryConnection.js
=> Airtable and Cloudinary Connection

server/controllers/index.js, server/controllers/routes/index.js, server/controllers/routes/intialResult.js, server/router/index.js
=> Initial Result Get

server/controllers/index.js, server/controllers/routes/filter.js, server/controllers/routes/index.js, server/controllers/utils/filerFunction.js, server/router/index.js
=> Create filter route and its function

package.json, server/app.js
=> Deploy Heroku

client/package-lock.json, client/package.json, client/src/components/App/index.js, client/src/components/pages/About/index.js, client/src/components/pages/Glossary/index.js, client/src/components/pages/NotFound/index.js, client/src/components/pages/Profile/index.js, client/src/components/pages/Results/index.js, client/src/components/pages/Signup/index.js, client/src/components/pages/TherapyType/index.js
relates #100
- add title to all react pages by using react helmet .
=> add title to all pages

client/src/components/App/index.js, client/src/components/common/Header/menuData.js
Relates #108 
Edit questionnaire route in app and menu
=> edit questionnaire route

client/src/components/common/Loader/index.js, client/src/components/common/Loader/style.css
- create simple Loader component 
relates #106
=> create simple loader component

client/src/components/pages/Profile/index.js
=> profile company insurance

client/src/components/common/Header/index.js
=> Fix menu bug

client/src/components/common/Loader/style.css, client/src/components/pages/Profile/index.js, client/src/components/pages/Results/index.js
- add loader component to places that do loading 
relates #114
=> add Loader component to pages that need loading

server/controllers/index.js, server/controllers/routes/cities.js, server/controllers/routes/index.js, server/router/index.js
=> create cities route

client/src/components/pages/Signup/index.js, client/src/components/pages/Signup/staticData.js
=> Edit insurance input

client/src/components/common/Header/style.css
=> fix menu in desktop screen

client/src/components/common/AvailabilityTime/style.css, client/src/components/common/Card/cardContent.js, client/src/components/common/Card/style.css, client/src/components/common/Filter/index.js, client/src/components/common/Header/style.css, client/src/components/common/Location/style.css, client/src/components/common/availabilityTable/style.css, client/src/components/pages/FilterPage/style.css, client/src/components/pages/Home/index.js, client/src/components/pages/Home/style.css, client/src/components/pages/Profile/index.js, client/src/components/pages/Profile/style.css
Make these pages responsive 
- Profile
- Home
- Filter
- Menu
=> Responsive and Style

client/src/components/pages/Home/index.js, client/src/components/pages/Home/style.css
- add new tagline to the home page as a description
relates #145
=> change tagline in homepage

client/src/components/common/index.js, client/src/components/pages/Signup/index.js, client/src/components/pages/Signup/style.css, server/controllers/routes/signup.js, server/controllers/validation/signupValidation.js
=> on submit signup

client/src/components/pages/Glossary/glossaryData.json, client/src/components/pages/Glossary/index.js, client/src/components/pages/Glossary/style.css
=> update glossary data and style

client/src/components/pages/QuestionaryPage/index.js
=> remove semicolon from Questionnaire page

client/src/components/pages/Home/index.js
=> change the route from types to questionnaire

client/src/components/common/Header/menuData.js, client/src/components/common/Header/style.css
- change menu items names as mentioned in user testing . 
- fix menu item height .
relates #169
=> change names for menu items

client/src/components/pages/Home/style.css
- raise the link up 
relates #171
=> edit link position

client/src/components/common/Filter/index.js, client/src/components/pages/FilterPage/index.js
- change sentences as required form user testing
relates #174
=> change statments in search page as required

client/src/components/pages/Home/index.js, client/src/components/pages/Home/style.css
- change the main description .
relates #176
=> change the main description in Front Page

client/src/components/common/FilterResult/staticData.js, client/src/components/pages/Results/index.js
=> add I to Integrative word

client/src/components/pages/Glossary/glossaryData.json, client/src/components/pages/Home/index.js
=> user testing changes

client/src/components/pages/TherapyType/staticData.js
=> add therapy types to static data

client/src/components/common/Card/style.css, client/src/components/common/Filter/style.css, client/src/components/pages/About/style.css, client/src/components/pages/FilterPage/index.js, client/src/components/pages/FilterPage/style.css, client/src/components/pages/Glossary/index.js, client/src/components/pages/Glossary/style.css, client/src/components/pages/Home/style.css, client/src/components/pages/QuestionaryPage/index.js, client/src/components/pages/QuestionaryPage/style.css, client/src/components/pages/TherapyType/style.css
=> General Look in style

client/src/components/pages/Glossary/index.js, client/src/components/pages/Glossary/style.css
=> search bar in glossary

server/app.js, server/controllers/routes/profile.js
Make back to return 404 error.
=> Bug in profile end point

README.md
=> fix display launch app locally

client/src/components/pages/About/index.js, client/src/components/pages/Home/index.js
- Buttons text needs capital letters removing!
- change text in about section
relates #208
=> do some changes | Prioritized changes  
